/** Auto-generated by scripts/generate-food-covers.mjs — do not edit by hand. */

export type FoodCoverPalette = {
  id: string;
  src: string;
  colors: [string, string, string];
  hue: number;
  color: string;
  backgroundColor: string;
};

export const FOOD_COVER_PALETTES = [
  {
    "id": "avocado",
    "src": "/covers/food/avocado.jpg?v=2",
    "colors": [
      "#bcac45",
      "#d1c469",
      "#8d883f"
    ],
    "hue": 54,
    "color": "#FAFAF8",
    "backgroundColor": "#b7ad56"
  },
  {
    "id": "basil",
    "src": "/covers/food/basil.jpg?v=2",
    "colors": [
      "#557e14",
      "#59811b",
      "#2e4a10"
    ],
    "hue": 84,
    "color": "#FAFAF8",
    "backgroundColor": "#62872b"
  },
  {
    "id": "beet",
    "src": "/covers/food/beet.jpg?v=2",
    "colors": [
      "#874f5c",
      "#3b161b",
      "#402027"
    ],
    "hue": 347,
    "color": "#FAFAF8",
    "backgroundColor": "#4d2930"
  },
  {
    "id": "berry",
    "src": "/covers/food/berry.jpg?v=2",
    "colors": [
      "#262530",
      "#6b2135",
      "#562b43"
    ],
    "hue": 308,
    "color": "#FAFAF8",
    "backgroundColor": "#432c40"
  },
  {
    "id": "bread",
    "src": "/covers/food/bread.jpg?v=2",
    "colors": [
      "#ccaf7b",
      "#a58960",
      "#ab804d"
    ],
    "hue": 35,
    "color": "#FAFAF8",
    "backgroundColor": "#a48252"
  },
  {
    "id": "chocolate",
    "src": "/covers/food/chocolate.jpg?v=2",
    "colors": [
      "#866868",
      "#5a322d",
      "#2c1a16"
    ],
    "hue": 6,
    "color": "#FAFAF8",
    "backgroundColor": "#5c3d3a"
  },
  {
    "id": "lemon",
    "src": "/covers/food/lemon.jpg?v=2",
    "colors": [
      "#e7d066",
      "#d5b23f",
      "#e1bb20"
    ],
    "hue": 48,
    "color": "#0A0A0A",
    "backgroundColor": "#ddbe48"
  },
  {
    "id": "olive",
    "src": "/covers/food/olive.jpg?v=2",
    "colors": [
      "#907a39",
      "#886f31",
      "#907527"
    ],
    "hue": 44,
    "color": "#FAFAF8",
    "backgroundColor": "#8a7029"
  },
  {
    "id": "peach",
    "src": "/covers/food/peach.jpg?v=2",
    "colors": [
      "#f1a04d",
      "#b45e35",
      "#c5703b"
    ],
    "hue": 25,
    "color": "#FAFAF8",
    "backgroundColor": "#d27b3d"
  },
  {
    "id": "pepper",
    "src": "/covers/food/pepper.jpg?v=2",
    "colors": [
      "#9c1c0f",
      "#c4352e",
      "#861f15"
    ],
    "hue": 5,
    "color": "#FAFAF8",
    "backgroundColor": "#9d2117"
  },
  {
    "id": "tomato",
    "src": "/covers/food/tomato.jpg?v=2",
    "colors": [
      "#dc5a3a",
      "#c73926",
      "#dd5438"
    ],
    "hue": 9,
    "color": "#FAFAF8",
    "backgroundColor": "#cd432b"
  },
  {
    "id": "yolk",
    "src": "/covers/food/yolk.jpg?v=2",
    "colors": [
      "#e8a022",
      "#e6a430",
      "#d29935"
    ],
    "hue": 38,
    "color": "#FAFAF8",
    "backgroundColor": "#db9f38"
  }
] as const satisfies ReadonlyArray<FoodCoverPalette>;
